// Generated by CoffeeScript 1.6.3
(function() {
  var $, IE6, Pop, body, defaultConfig, document, getFullHeight, getPostype, window;

  $ = jQuery;

  window = $(this);

  document = $(document);

  body = $('body');

  IE6 = !-[1] && !window.XMLHttpRequest;

  getPostype = function() {
    return IE6 ? 'absolute' : 'fixed';
  };

  getFullHeight = function() {
    if (window.height() > body.height()) {
      return window.height();
    }
    return body.height();
  };

  Pop = function(target, opts) {
    this.target = target;
    this.settings = opts;
    this.timer = null;
    this.init();
  };

  Pop.prototype = {
    init: function() {
      var opts, that;
      that = this;
      opts = that.settings;
      that.closePrevPop();
      opts.beforeCallback(that);
      if (opts.isColseBtn) {
        that.createClose();
      }
      if (opts.isLock) {
        that.createLock();
      }
      if (typeof opts.time === 'number') {
        that.timer = setTimeout(function() {
          that.closePop();
        }, opts.time);
      }
      that.bindEvent();
      that.showTarget();
    },
    showTarget: function() {
      var left, obj, opts, that, top;
      that = this;
      obj = that.target;
      opts = that.settings;
      obj.addClass('prevPopBox').show();
      if (opts.middile) {
        left = Math.round((body.width() - obj.outerWidth()) / 2);
        top = Math.round((window.height() - obj.outerHeight()) / 2);
        obj.css({
          'position': getPostype(),
          'left': left,
          'top': top,
          'z-index': opts.zIndex + 1
        });
      }
    },
    createLock: function() {
      var opts, popLock, that;
      that = this;
      opts = that.settings;
      popLock = $('#QpopLock');
      if (popLock.length > 0) {
        popLock.show();
        return;
      }
      popLock = that.Lock = $('<div id="QpopLock"></div>');
      popLock.css({
        'position': 'absolute',
        'top': 0,
        'left': 0,
        'width': '100%',
        'height': '100%',
        'background-color': opts.lockBgColor,
        'opacity': opts.opacity,
        'z-index': opts.zIndex
      });
      if (IE6) {
        that.createIframe(popLock);
      }
      body.append(popLock);
    },
    createIframe: function(elem) {
      elem.html('<iframe style="position:absolute;left:0;top:0;width:100%;height:100%;z-index:-1;border:0 none;filter:alpha(opacity=0)"></iframe>');
    },
    createClose: function() {
      var closeBtn;
      closeBtn = this.closeBtn = $('<a class="popCloseBtn">关闭</a>');
      this.target.append(closeBtn);
    },
    bindEvent: function() {
      var that;
      that = this;
      if (that.closeBtn) {
        that.closeBtn.bind('click', function() {
          that.closePop();
        });
      }
      if (that.Lock && that.lockColse) {
        that.Lock.bind('click', function() {
          that.closePop();
        });
      }
    },
    closePop: function() {
      var that;
      that = this;
      clearTimeout(that.timer);
      if (that.Lock) {
        that.Lock.remove();
      }
      if (that.closeBtn) {
        that.closeBtn.remove();
      }
      that.target.removeClass('prevPopBox').hide();
      that.settings.colseCallback.call(that);
    },
    closePrevPop: function() {
      body.find('.prevPopBox').hide().removeClass('prevPopBox');
    }
  };

  defaultConfig = {
    zIndex: 999,
    middile: true,
    isLock: true,
    lockColse: false,
    lockBgColor: '#000',
    opacity: 0.5,
    time: null,
    isColseBtn: true,
    colseCallback: function() {},
    beforeCallback: function() {}
  };

  $.fn.QPop = function(opts) {
    opts = $.extend({}, defaultConfig, opts);
    return this.each(function() {
      return new Pop($(this), opts);
    });
  };

}).call(this);
